USE [master]
GO

/****** Object:  Database [SQL_Projekat_DexyCO]    Script Date: 15-Feb-21 3:41:11 PM ******/
CREATE DATABASE [SQL_Projekat_DexyCO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQL_Projekat_DexyCO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\SQL_Projekat_DexyCO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SQL_Projekat_DexyCO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\SQL_Projekat_DexyCO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQL_Projekat_DexyCO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET RECOVERY FULL 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET  MULTI_USER 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SQL_Projekat_DexyCO] SET  READ_WRITE 
GO

