USE [SQL_Projekat_DexyCO]
GO

/****** Object:  Table [dbo].[TIpIgracke]    Script Date: 16-Feb-21 1:58:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIpIgracke](
	[tipID] [int] IDENTITY(1,1) NOT NULL,
	[nazivTipa] [nvarchar](50) NOT NULL,
	[zaDveiliVise] [bit] NOT NULL,
 CONSTRAINT [PK_TIpIgracke] PRIMARY KEY CLUSTERED 
(
	[tipID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

